### ISSUE TITLE
STT0028: upload stt combine all dataset to monlam ai organization

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/stt-spoken-to-written#1]
### Description
split the stt combine dataset into csv files of range 1000. each csv file should have file_name, inference transcript, written transcript.
### Completion Criteria
uploaded in monlam ai
### Subtasks
- [x] extract combine all dataset
- [x] split combine all data set 
- [x] upload to monlam ai
